import { normCardList, NormedCard } from 'mtgql'

export const COBRA_CUSTOM_ID = 'custom-card'
export const DEFAULT_CUSTOM_CARD: NormedCard = normCardList([{
  id: COBRA_CUSTOM_ID,
  oracle_id: COBRA_CUSTOM_ID,
  name: 'Custom Card',
  printed_name: undefined,
  lang: 'en',
  set: '',
  set_name: '',
  collector_number: '',
  released_at: '',
  reprint: false,
  border_color: 'black',
  promo: false,
  promo_types: [],
  digital: false,
  finishes: [],
  prices: {
    usd: null,
    usd_foil: null,
    usd_etched: null,
    eur: null,
    tix: null,
  },
  image_uris: {
    small: '',
    png: '',
    border_crop: '',
    normal: 'https://cubecobra.com/content/custom_card.png',
    large: 'https://cubecobra.com/content/custom_card.png',
    art_crop: 'https://cubecobra.com/content/custom_card_art_crop.png',
  },
  card_faces: undefined,
  loyalty: undefined,
  power: undefined,
  toughness: undefined,
  type_line: '',
  oracle_text: '',
  mana_cost: '',
  cmc: 0,
  colors: [],
  color_identity: [],
  keywords: [],
  produced_mana: [],
  legalities: {
    standard: 'not_legal',
    historic: 'not_legal',
    pioneer: 'not_legal',
    modern: 'not_legal',
    legacy: 'not_legal',
    pauper: 'not_legal',
    vintage: 'not_legal',
    penny: 'not_legal',
    commander: 'not_legal',
    brawl: 'not_legal',
  },
  layout: 'normal',
  rarity: 'common',
  artist: '',
  scryfall_uri: '',
  mtgo_id: 0,
  textless: false,
  tcgplayer_id: '',
  full_art: false,
  flavor_text: '',
  frame_effects: [],
  frame: '',
  card_back_id: '',
  artist_id: '',
  illustration_id: '',
  content_warning: false,
  variation: false,
  preview: {
    source: '',
    source_uri: '',
    previewed_at: '',
  },
  related_uris: {
    gatherer: '',
    tcgplayer_decks: '',
    edhrec: '',
    mtgtop8: '',
  },
  all_parts: [],
  object: 'card',
}])[0]